"""Moved photo_url from User to Horse where it belongs

Revision ID: 2db69f930d50
Revises: cbe7620da972
Create Date: 2023-10-06 10:40:51.305810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db69f930d50'
down_revision = 'cbe7620da972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
