"""Creates Horse,MorningFeed,EveningFeed tables

Revision ID: 6607d1c18d9c
Revises: d0567c647b84
Create Date: 2023-10-06 07:15:33.436567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6607d1c18d9c'
down_revision = 'd0567c647b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evening_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfalfaFlakes', sa.Integer(), nullable=True),
    sa.Column('grassHayFlakes', sa.Integer(), nullable=True),
    sa.Column('grainPounds', sa.Integer(), nullable=True),
    sa.Column('grainType', sa.String(), nullable=True),
    sa.Column('feedNotes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfalfaFlakes', sa.Integer(), nullable=True),
    sa.Column('grassHayFlakes', sa.Integer(), nullable=True),
    sa.Column('grainPounds', sa.Integer(), nullable=True),
    sa.Column('grainType', sa.String(), nullable=True),
    sa.Column('feedNotes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vetName', sa.String(), nullable=False),
    sa.Column('vetNumber', sa.String(), nullable=False),
    sa.Column('careNotes', sa.String(), nullable=True),
    sa.Column('morning_feed_id', sa.Integer(), nullable=True),
    sa.Column('evening_feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evening_feed_id'], ['evening_feeds.id'], name=op.f('fk_horses_evening_feed_id_evening_feeds')),
    sa.ForeignKeyConstraint(['morning_feed_id'], ['morning_feeds.id'], name=op.f('fk_horses_morning_feed_id_morning_feeds')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horses')
    op.drop_table('morning_feeds')
    op.drop_table('evening_feeds')
    # ### end Alembic commands ###
