"""Reset of the database to allow snake case not camel case (we b python) and add photo_url to horse.

Revision ID: cbe7620da972
Revises: 
Create Date: 2023-10-06 08:26:32.326296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe7620da972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evening_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfalfa_flakes', sa.Integer(), nullable=True),
    sa.Column('grass_hay_flakes', sa.Integer(), nullable=True),
    sa.Column('grain_pounds', sa.Integer(), nullable=True),
    sa.Column('grain_type', sa.String(), nullable=True),
    sa.Column('feed_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfalfa_flakes', sa.Integer(), nullable=True),
    sa.Column('grass_hay_flakes', sa.Integer(), nullable=True),
    sa.Column('grain_pounds', sa.Integer(), nullable=True),
    sa.Column('grain_type', sa.String(), nullable=True),
    sa.Column('feed_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vet_name', sa.String(), nullable=False),
    sa.Column('vet_number', sa.String(), nullable=False),
    sa.Column('care_notes', sa.String(), nullable=True),
    sa.Column('morning_feed_id', sa.Integer(), nullable=True),
    sa.Column('evening_feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evening_feed_id'], ['evening_feeds.id'], name=op.f('fk_horses_evening_feed_id_evening_feeds')),
    sa.ForeignKeyConstraint(['morning_feed_id'], ['morning_feeds.id'], name=op.f('fk_horses_morning_feed_id_morning_feeds')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_users_horses_horse_id_horses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_horses_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_horses')
    op.drop_table('horses')
    op.drop_table('users')
    op.drop_table('morning_feeds')
    op.drop_table('evening_feeds')
    # ### end Alembic commands ###
